apiVersion: apps/v1
kind: Deployment
metadata:
  name: lottery-ticket-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lottery-ticket-catalog
  template:
    metadata:
      labels:
        app: lottery-ticket-catalog
    spec:
      containers:
        - image: prporso/image-catalog:test #to be changed
          name: lottery-ticket-catalog
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: #connection url
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: #username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              #value: #password
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: #to be added
                  key: #to be added
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: lottery-ticket-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: lottery-ticket-catalog
