apiVersion: apps/v1
kind: Deployment
metadata:
  name: lottery-ticket-catalog-deployment
  namespace: rso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lottery-ticket-catalog
  template:
    metadata:
      labels:
        app: lottery-ticket-catalog
    spec:
      containers:
        - image: lb4684/lottery-ticket-catalog:latest
          name: lottery-ticket-catalog
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://sqlsimplsrecka.postgres.database.azure.com:5432/lottery-ticket
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: lukaariana
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lottery-ticket-secret
                  key: password
          ports:
            - containerPort: 8081
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: lottery-ticket-catalog
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: lottery-ticket-catalog

