kumuluzee:
  name: lottery-ticket-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http:/localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/LotteryTicketDS
      #connection-url: jdbc:postgresql://localhost:5432/lottery-ticket
      connection-url: jdbc:postgresql://sqlsimplsrecka.postgres.database.azure.com:5432/lottery-ticket
      username: lukaariana
      #password: ${{ secrets.AZURE_CREDENTIALS }}
      #username: dbuser
      password: XonaryLu99
      pool:
        max-size: 4
  dev:
    scan-libraries:
      - lottery-ticket-catalog-models
      - lottery-ticket-catalog-services
      - lottery-ticket-catalog-lib
  openapi-mp:
    ui:
      specification-server: http://52.226.192.46/lottery-ticket-catalog
      #mapping: /lottery-ticket-catalog/api-specs/ui
  graphql:
    ui:
      mapping: /lottery-ticket-catalog/graphiql
      enabled: true
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/LotteryTicketDS
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  metrics:
    web-instrumentation:
      - name: tickets-endpoint
        url-pattern: /v1/lottery/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="SimplSrecka">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="ce34edf9-867c-4db8-a4b0-274615f77e3f-ls.logit.io"
                                    port="19822" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
rest-properties:
  broken: false